### ISSUE TITLE
Tracking the components needed to refresh rpaframework-feedstock

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/rpaframework-feedstock#34]
Checklist
- [x] uiautomation source distribution on pypi 
   https://files.pythonhosted.org/packages/a0/4d/95492682701c5d0276f5aa2707afffe6d52619e0526af48e639046c413c4/uiautomation-2.0.18.tar.gz
- [x] refresh rpaframework-core
   https://github.com/conda-forge/rpaframework-core-feedstock/pull/25
- [x] refresh rpaframework-pdf
   https://github.com/conda-forge/rpaframework-pdf-feedstock/pull/6
- [x] refresh pynput-robocorp-fork-feedstock
   https://github.com/conda-forge/pynput-robocorp-fork-feedstock/pull/7
- [x] build and publish uiautomation 
   https://github.com/conda-forge/uiautomation-feedstock
   https://anaconda.org/conda-forge/uiautomation
- [x] build and publish java-access-bridge-wrapper
   https://github.com/conda-forge/java-access-bridge-wrapper-feedstock
   https://anaconda.org/conda-forge/java-access-bridge-wrapper

HI @osrjv 
uiautomation is going to be the tricky one - I have asked to see if they are willing to help - starting with a usable source distribution on pypi, I have an issue on their board. 

As of the overall state - here are my notes - quite a long way to go - hope this helps. I have comments below on the packages that are missing - # Missing on Conda-Forge

| Package                            | Version                 | Arch      | conda-forge | Status  | Version |
|------------------------------------|-------------------------|-----------|-------------|---------|---------|
| chardet                            | >=3.0.0,<4.0.0          |           |             |         |         |
| click                              | >=8.1.2,<9.0.0          |           |             |         |         |
| comtypes                           | >=1.1.11,<2.0.0         |   # [win] |             |         |         |
| cryptography                       | >=41.0.3,<42.0.0        |           |             |         |         |
| docutils                           |                         |           |             |         |         |
| exchangelib                        | >=4.7.6,<5.0.0          |           |             |         |         |
| holidays                           | >=0.21.0,<0.22.0        |           |             |         |         |
| htmldocx                           | >=0.0.6,<0.0.7          |           | # Missing   | Done    | 0.0.6   |
| hubspot-api-client                 | >=4.0.6,<5.0.0          |           | # Missing   | Done    | 4.0.6   |
| importlib-metadata                 | >=4.13.0,<5.0.0         |           |             |         |         |
| java-access-bridge-wrapper         | 0.14.1                  |   # [win] | # Missing   | Done    | 0.14.1  |
| jsonpath-ng                        | >=1.5.2,<2.0.0          |           |             |         |         |
| netsuitesdk                        | >=1.1.0,<2.0.0          |           |             |         |         |
| notifiers                          | >=1.3.3,<2.0.0          |           |             |         |         |
| o365                               | >=2.0.21,<2.0.27        |           |             |         |         |
| oauthlib                           | >=3.2.2,<4.0.0          |           |             |         |         |
| openpyxl                           | >=3.0.9,<4.0.0          |           |             |         |         |
| pendulum                           | >=2.1.2,<3.0.0          |           |             |         |         |
| pillow                             | >=9.1.1,<10.0.0         |           |             |         |         |
| psutil                             | >=5.7.0,<6.0.0          |           |             |         |         |
| pyjwt                              | >=2.6.0,<3.0.0          |           |             |         |         |
| pynput-robocorp-fork               | >=2.0.0,<6.0.0          |           | # Outdated  | Done    | 5.0.0   |
| pyotp                              | >=2.6.0,<3.0.0          |           |             |         |         |
| pyperclip                          | >=1.8.0,<2.0.0          |           |             |         |         |
| pysocks                            | >=1.5.6,!=1.5.7,<2.0.0  |           |             |         |         |
| python-graphviz                    | >=0.13.2,<0.14.0        |           |             |         |         |
| python-mss                         | >=6.0.0,<7.0.0          |           |             |         |         |
| python-xlib                        | >=0.17                  |           |             |         |         |
| pywin32-on-windows                 |                         |   # [win] |             |         |         |
| pywinauto                          | >=0.6.8,<0.7.0          |   # [win] |             |         |         |
| pyyaml                             | >=5.4.1,<7.0.0          |           |             |         |         |
| requests                           | >=2.28.1,<3.0.0         |           |             |         |         |
| requests-oauthlib                  | >=1.3.1,<2.0.0          |           |             |         |         |
| robocorp-storage                   | >=0.3.2,<0.4.0          |           | # Missing   | Done    | 0.3.2   |
| robotframework                     | >=4.0.0,!=4.0.1,<6.0.0  |           |             |         | 6.1.1   |
| robotframework-pythonlibcore       | >=4.0.0,<5.0.0          |           |             |         | 4.2.0   |
| robotframework-requests            | >=0.7.2,<0.10.0         |           | # Outdated  |         | 0.7.2   |
| robotframework-sapguilibrary       | >=1.1.0,<2.0.0          |           | # Outdated  |         | 1.1     |
| robotframework-seleniumlibrary     | >=6.0.0,<7.0.0          |           |             |         | 6.1.2   |
| robotframework-seleniumtestability | >=2.0.0,<3.0.0          |           |             |         | 2.1.0   |
| rpaframework-core                  | >=11.0.5,<12.0.0        |           | # Outdated  | Done    | 11.0.5  |
| rpaframework-pdf                   | >=0.3.1,<8.0.0          |           | # Outdated  | Done    | 7.2.0   |
| rpaframework-windows               | >=7.3.2,<8.0.0          |   # [win] | # Missing   | Pending | 7.3.2   |
| selenium                           | >=4.6.1,<5.0.0,!=4.10.0 |           |             |         | 4.12.0  |
| simple-salesforce                  | >=1.0.0,<2.0.0          |           |             |         |         |
| smartsheet-python-sdk              | >=3.0.0,<4.0.0          |           | # Missing   | Done    | 3.0.2   |
| tenacity                           | >=8.0.1,<9.0.0          |           |             |         |         |
| tweepy                             | >=3.8.0,<4.0.0          |           |             |         |         |
| tzlocal                            | >=4.2.0,<5.0.0          |           |             |         |         |
| uiautomation                       | >=2.0.15,<3.0.0         |   # [win] | # Missing   | Done    | 2.0.18  |
| validators                         | >=0.20.0,<0.21.0        |           |             |         |         |
| xlrd                               | >=2.0.1,<3.0.0          |           |             |         |         |
| xlutils                            | >=2.0.0,<3.0.0          |           |             |         |         |

Thanks and regards. 

```
{% set name = "rpaframework" %}
{% set version = "25.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework-{{ version }}.tar.gz
  sha256: becb40d0ab49b54a683905407d790fcae75d681412cf25f3f9932f6abfec39b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  #skip: true  # [py>=40 or py2k]
  #entry_points:
    #- rpa-google-oauth = RPA.scripts.google_authenticate:start

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - docutils
    - rpaframework-core >=11.0.5,<12.0.0
#    - rpaframework-pdf >=0.3.1,<8.0.0
#- nothing provides requested rpaframework-pdf >=7.1.6,<8.0.0  # 0.3.1
#- package rpaframework-pdf-0.3.1-pyhd8ed1ab_0 requires rpaframework-core >=6.1.0,<7.0.0, but none of the providers can be installed # https://github.com/conda-forge/rpaframework-core-feedstock/pull/25
    #- rpaframework-windows >=7.3.2,<8.0.0  # Missing on Conda-Forge
    #- uiautomation >=2.0.15,<3.0.0  # Missing on Conda-Forge
    #- java-access-bridge-wrapper 0.14.1  # Missing on Conda-Forge
    #- robocorp-storage >=0.3.2,<0.4.0  # Missing on Conda-Forge
    - jsonpath-ng >=1.5.2,<2.0.0
    - robotframework >=4.0.0,!=4.0.1,<6.0.0
#    - robotframework-sapguilibrary >=1.1.0,<2.0.0  # [win]
#- nothing provides requested robotframework-sapguilibrary >=1.1.0,<2.0.0  # [win]
    - robotframework-seleniumlibrary >=6.0.0,<7.0.0
    - robotframework-seleniumtestability >=2.0.0,<3.0.0
    - robotframework-requests >=0.7.2,<0.10.0
#- nothing provides requested robotframework-requests >=0.9.1,<0.10.0  # 0.7.2
    - pywinauto >=0.6.8,<0.7.0
#    - pywinauto >=0.6.8,<0.7.0  # [py<37 and win or py>37 and py<38 and win or py>38 and win]
    - pywin32-on-windows # >=302,<304 # Note Version is 0.1.0
#    - pywin32-on-windows # >=302,<304  # [py>=37 and win]
#    - comtypes >=1.1.11,<2.0.0  # [win]
#- nothing provides requested comtypes >=1.1.11,<2.0.0  # [win]
    - robotframework-pythonlibcore >=4.0.0,<5.0.0
    - pynput-robocorp-fork >=2.0.0,<6.0.0
#- nothing provides requested pynput-robocorp-fork >=5.0.0,<6.0.0  #  2.0.0
    - python-xlib >=0.17
#    - python-xlib >=0.17  # [linux]
    - psutil >=5.7.0,<6.0.0
#    - psutil >=5.7.0,<6.0.0  # [win]
    - pyperclip >=1.8.0,<2.0.0
    - exchangelib >=4.7.6,<5.0.0
    - tzlocal >=4.2.0,<5.0.0
    - xlrd >=2.0.1,<3.0.0
    - xlwt >=1.3.0,<2.0.0
    - xlutils >=2.0.0,<3.0.0
    - openpyxl >=3.0.9,<4.0.0
    - pillow >=9.1.1,<10.0.0
    - simple-salesforce >=1.0.0,<2.0.0
    - netsuitesdk >=1.1.0,<2.0.0
    - tweepy >=3.8.0,<4.0.0
    - python-graphviz >=0.13.2,<0.14.0
    - notifiers >=1.3.3,<2.0.0
    - cryptography >=41.0.3,<42.0.0
    - python-mss >=6.0.0,<7.0.0
    - chardet >=3.0.0,<4.0.0
    - pysocks >=1.5.6,!=1.5.7,<2.0.0
    - selenium >=4.6.1,<5.0.0,!=4.10.0
    - click >=8.1.2,<9.0.0
    - pyyaml >=5.4.1,<7.0.0
    - tenacity >=8.0.1,<9.0.0
    #- htmldocx >=0.0.6,<0.0.7  # Missing on Conda-Forge
    #- hubspot-api-client >=4.0.6,<5.0.0  # Missing on Conda-Forge
    - pyotp >=2.6.0,<3.0.0
    - importlib-metadata >=4.13.0,<5.0.0
    - o365 >=2.0.21,<2.0.27
    - requests >=2.28.1,<3.0.0
    - oauthlib >=3.2.2,<4.0.0
    - requests-oauthlib >=1.3.1,<2.0.0
    - pyjwt >=2.6.0,<3.0.0
    - validators >=0.20.0,<0.21.0
    #- smartsheet-python-sdk >=3.0.0,<4.0.0  # Missing on Conda-Forge
    - pendulum >=2.1.2,<3.0.0
    - holidays >=0.21.0,<0.22.0

test:
  source_files:
    #- tests
  imports:
    - RPA
    - RPA.Browser
  commands:
    #- pytest -k "not browser and not pdf" tests/
    # - pip check  # [linux]
    # google-oauth is optional dependency, script fails if it's not installed
    # - rpa-google-oauth --help
  requires:
    - pip
    - mock >=2
    - pytest >=3.4,!=3.10.0
    - pytest-mock >=1.8
    - pytest-cov

about:
  home: https://rpaframework.org/
  summary: A collection of tools and libraries for RPA
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
```

_Originally posted by @rxm7706 in https://github.com/conda-forge/rpaframework-core-feedstock/issues/25#issuecomment-1695389093_
